In [3]:
import torch
import torch.nn.functional as F
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]])

kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])
print(input.shape)# torch.Size([5, 5])
print(kernel.shape)# torch.Size([3, 3])
input = torch.reshape(input,(1,1,5,5))
kernel = torch.reshape(kernel,(1,1,3,3))
print(input.shape)# torch.Size([1, 1, 5, 5])
print(kernel.shape)# torch.Size([1, 1, 5, 5])

# 基本卷积操作的实现
output = F.conv2d(input,kernel,stride=1)
print(output)
# tensor([[[[10, 12, 12],
#           [18, 16, 16],
#           [13,  9,  3]]]])

torch.Size([5, 5])
torch.Size([3, 3])
torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])
tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [5]:
output2 = F.conv2d(input,kernel,stride=2)
print(output2)
# tensor([[[[10, 12],
#           [13,  3]]]])

tensor([[[[10, 12],
          [13,  3]]]])


In [6]:
output3 = F.conv2d(input,kernel,stride=1,padding=1)
print(output3)
# tensor([[[[ 1,  3,  4, 10,  8],
#           [ 5, 10, 12, 12,  6],
#           [ 7, 18, 16, 16,  8],
#           [11, 13,  9,  3,  4],
#           [14, 13,  9,  7,  4]]]])

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])


In [ ]:
在图像数据集上进行操作：

In [12]:
import torch
import torchvision #引入torchvision.datasets
from torch.utils.data import DataLoader
from torch import nn  #引入nn.Module
from torch.nn import Conv2d
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10("./dataset",train=False,transform=torchvision.transforms.ToTensor(),download=True)
dataloader = DataLoader(dataset,batch_size=64)
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = Conv2d(in_channels=3,out_channels=6,kernel_size=3,stride=1,padding=0)
    def forward(self,x):
        x = self.conv1(x)
        return x
  
step = 0
writer = SummaryWriter('log_conv2d')
model = Model()#定义一个类对象
# print(model)# Model( (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1)) )
for data in dataloader:
    imgs,targets=data
    output = model(imgs)
    output = torch.reshape(output,(-1,3,30,30))
#     print(imgs.shape)#torch.Size([64, 3, 32, 32])
#     print(output.shape)#torch.Size([64, 6, 30, 30])
    writer.add_images("input",imgs,step)
    writer.add_images("output",output,step)
    step += 1
    writer.close()
    

Files already downloaded and verified
