In [3]:
import torch
from torch import nn
from torch.nn import ReLU

input = torch.tensor([[1,-0.5],
                     [-1,3]])

input = torch.reshape(input,(-1,1,2,2))
# print(input)
# print(input.shape)
# tensor([[[[ 1.0000, -0.5000],
#           [-1.0000,  3.0000]]]])
# torch.Size([1, 1, 2, 2])

class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.relu1 = ReLU()#inplace默认为False
        
    def forward(self,input):
        output = self.relu1(input)
        return output
    
model = Model()
output = model(input)
print(output)
# tensor([[[[1., 0.],
#           [0., 3.]]]])

tensor([[[[1., 0.],
          [0., 3.]]]])


In [12]:
import torchvision
from torch.utils.data import DataLoader
from torch.nn import Sigmoid
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10("./dataset",train=False,download=True,transform=torchvision.transforms.ToTensor())
dataloader = DataLoader(dataset,batch_size=64)

class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.sigmoid1 = Sigmoid()
        
    def forward(self,input):
        output = self.sigmoid1(input)
        
        return output
step = 0
writer = SummaryWriter("log_sig")
for data in dataloader:
    imgs,targets = data
#     print(imgs)
    writer.add_images("input",imgs,step)
    output = model(imgs)
    writer.add_images("output",output,step)
    step += 1
writer.close()


Files already downloaded and verified
